spring:
  application:
    name: vet
  h2:
    console:
      enabled: true
      path: /console/
  data:
    mongodb:
      host: localhost
      database: petclinic
      port: 27017
  activiti:
    processDefinitionLocationPrefix:  classpath*:process-defs/**.xml
  mvc:
    view:
      prefix: /
      suffix: .jsp
  sqldatasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver

application:
  error:
    genericMsg: System Error ERR.UNIQUEID
#  exceptions:
#    com.antheminc.oss.nimbus.FrameworkRuntimeException: Runtime Exception - ERR.UNIQUEID
#    genericMsg: ERR.UNIQUEID - System Error. ## Can use ERR.UNIQUEID as a placeholder to replace the uniqueId for error.

##Logging properties
#logging.file=${LOG_DIR_PATH}/${spring.application.name}.log
#logging.file=/var/tmp/nimbus/logs/${spring.application.name}.log

## Petclinic Env properties
petclinic:
  clinicname: PugsAndPaws
logging:
  file: ${HOME}/Documents/nimbuslogs/${spring.application.name}.log
  level:
    reactor.io.net.impl.netty.tcp: DEBUG
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } [%X{SESSIONID:- }] --- [%t] %-40.40logger{39} : %n${LOG_EXCEPTION_CONVERSION_WORD: %wEx}"  
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } [%X{SESSIONID:- }] --- [%t] %-40.40logger{39} : %n${LOG_EXCEPTION_CONVERSION_WORD: %wEx}"
  
#logging.level.org.springframework=DEBUG

jwt:
  secret: nimbustest
  algorithm: HS512
  
process:
  key:
    regex:
     ([A-Za-z0-9_\\-\\*~\\?=\\.\\$]+)
  database:
    driver: 
      embeddedH2
    url: 
      embeddedH2
    username: 
      embeddedH2
    password: 
      embeddedH2
    taskUpdateQuery:
      update ACT_RU_TASK set TASK_DEF_KEY_ = ?, NAME_ = ? WHERE ID_=?
    executionUpdateQuery:
      update ACT_RU_EXECUTION set ACT_ID_ = ?  WHERE ID_=? AND ACT_ID_=?   
  history:
    level: 
      full
  definitions:
   - classpath*:process-defs/**.xml
  rules:
   - rules/**.drl  
  customDeployers:

platform:
  config:
    cookies:
      gateway:
        name: GATEWAYSESSIONID
        path: /
    
      api:
        name: APISESSIONID
        path: /

      sticky:
        name: STICKYSERVERID
        path: /
    secure:
      regex: "^[a-zA-Z0-9<>()\\[\\]@/: &.=?,$#_-]{1,1000}" 
server:
  port: 8084
  servlet:
    context-path: /petclinic


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
#    instance-id: localhost:8084
domain:
  model:
    basePackages: 
      - com.antheminc.oss.nimbus.entity
      - com.atlas.client.extension.petclinic.core.home
      - com.atlas.client.extension.petclinic.core.veterinarian
      - com.atlas.client.extension.petclinic.view.veterinarian
      - com.atlas.client.extension.petclinic.view.home
      - com.atlas.client.extension.petquestionnaire.core
      - com.atlas.client.extension.petquestionnaire.view
#    basePackagesToExclude:
#      - com.atlas.client.extension.petclinic.core.owner
#      - com.atlas.client.extension.petclinic.core.pet
#      - com.atlas.client.extension.petclinic.view.owner
#      - com.atlas.client.extension.petclinic.view.pet


    typeClassMappings:
      java.lang.String : 
        string
    includeFilter: ['a','b']
    persistenceStrategy: ATOMIC
  action: abc
    
  validation:
    markerAnnotations:
      javax.validation.Constraint
    markerInterfaces:
   
#logging:
#  file: ${HOME}/Documents/nimbuslogs/platform-core-web.log
user:
  permissionToActions:
    ACCESS:
      _get,_info,_search,_new,_replace,_update,_delete,_nav,_process
    READ:
      _get,_info,_search,_getAll,_nav,_process
    CREATE:
      _new,_nav,_process
    UPDATE:
      _update,_replace,_nav,_process
    DELETE:
      _delete,_nav,_process

model:
  persistence:
    strategy:
      mode:
        ATOMIC
dsl:
  behavior:
    extensions:
      #$execute:
        #$save   
search:
  threshold:
    50
